name: 'update-repo'
description: |
  Update a CRAN-like repository, where packages are stored as GitHub
  release assets.

inputs:
  directory:
    default: "."
    description: |
      Directory of the repository.
  token:
    description: |
      GitHub access token for the deployment.

runs:
  using: "composite"
  steps:
  - name: Set user library location
    run: |
      #
      cat("::group::Set user library location\n")
      dir.create(lib <- Sys.getenv("R_LIBS_USER"), showWarnings = FALSE, recursive = TRUE)
      writeLines(paste0("R_LIBS_USER=", Sys.getenv("R_LIBS_USER")), Sys.getenv("GITHUB_ENV"))
      cat("::endgroup::\n")
    shell: Rscript {0}

  - uses: r-lib/actions/setup-r-dependencies@v2
    with:
      packages: r-lib/pkgdepends@feature/builder, gh, pkgsearch, withr, yaml, glue
      dependencies: NA
      pak-version: devel

  - name: Update repo
    run: |
      setwd("${{ inputs.directory }}")
      conf <- yaml::read_yaml("config.yaml")
      if (is.null(conf$packages)) {
        stop("`packages` missing or empty in `config.yaml`.")
      }
      if (is.null(conf$release_org)) conf$release_org <- "cran"
      if (is.null(conf$source)) conf$source <- "https://cran.r-project.org"
      pkgdepends:::ghrepo$update(
        "${{ github.repository }}",
        "${{ inputs.directory }}",
        release_org = conf$release_org,
        source_repo = conf$source,
        packages = conf$packages
      )
    shell: Rscript {0}
    env:
      GITHUB_PAT: ${{ inputs.token }}
