
source: https://cran.r-project.org
release_org: cran
packages:
  - bookdown
  - devtools
  - Hmisc
  - igraph
  - mvtnorm
  - pkgdown
  - rgeos
  - rgl
  - RSQLite
  - sf
  - shiny
  - tidymodels
  - tidyverse
  - zoo
