
source: https://cran.r-project.org
release_org: cran
packages:
  # tidyverse stuff
  - devtools
  - bookdown
  - pkgdown
  - shiny
  - tidymodels
  - tidyverse
  # most downloaded
  - Hmisc
  - igraph
  - mvtnorm
  - rgeos
  - rgl
  - sf
  - terra
  - zoo
  # most depended on
  - abind
  - ape
  - assertthat
  - BH
  - car
  - caret
  - coda
  - cowplot
  - digest
  - doParallel
  - DT
  - ggrepel
  - glmnet
  - gtools
  - kableExtra
  - lme4
  - markdown
  - matrixStats
  - plotly
  - plyr
  - png
  - pracma
  - R.rsp
  - randomForest
  - raster
  - RcppArmadillo
  - RcppEigen
  - Rdpack
  - reshape2
  - sp
  - spelling
  - tinytest
  - vdiffr
  - XML
  - zoo
  # takes long to build
  - arrow
  - duckdb
  - rstanarm
  # fails to build with non-standard compilers
  - tripack
