
source: https://cloud.r-project.org/
release_org: cran
packages:
  # tidyverse stuff
  - bit64
  - hms
  - tidyverse
  - pkgbuild
  # most downloaded
  # most depended on
  - spelling
  - testthat
  # takes long to build
  # fails to build with non-standard compilers
