name: macOS x86_64, R 4.4
on:
  workflow_dispatch:
  schedule:
    - cron:  '23 17 * * *'

jobs:
  update:
    runs-on: macos-13
    env:
      HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: true
    steps:
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: 'devel'
    - name: Check Distro and R version
      run: |
        #
        if (Sys.info()[["sysname"]] != "Darwin") stop("Not macOS")
        if (getRversion() < "4.4.0" || getRversion() >= "4.5.0") {
          stop("Not R 4.4.x")
        }
        if (Sys.info()[["machine"]] != "x86_64") stop("Not x86_64")
      shell: Rscript {0}
    - uses: actions/checkout@v4
    - uses: r-hub/repos/actions/update-repo@main
      with:
        directory: macos-x86_64/4.4
        token: ${{ secrets.CRANATGH_GITHUB_TOKEN }}
