
name: Ubuntu 22.04, R 4.4
on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    container: ghcr.io/r-hub/containers/ubuntu-gcc12:latest
    steps:
    - uses: actions/checkout@v3
    - uses: r-hub/repos/actions/update-repo@main
      with:
        directory: ubuntu-22.04/4.4
        token: ${{ secrets.CRANATGH_GITHUB_TOKEN }}
