name: Ubuntu 22.04 aarch64, R 4.4
on:
  workflow_dispatch:
  schedule:
    - cron:  '23 18 * * *'

jobs:
  update:
    runs-on: [ARM64]
    container: ghcr.io/r-lib/rig/ubuntu-22.04-devel
    steps:
    - uses: actions/checkout@v3
    - uses: r-hub/repos/actions/update-repo@main
      with:
        directory: ubuntu-22.04-aarch64/4.4
        token: ${{ secrets.CRANATGH_GITHUB_TOKEN }}
