
name: Ubuntu 22.04, R 4.4, libc++
on:
  workflow_dispatch:
  schedule:
    - cron:  '53 16 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    container: ghcr.io/r-hub/containers/clang16:latest
    steps:
    - uses: actions/checkout@v3
    - uses: r-hub/repos/actions/update-repo@main
      with:
        directory: ubuntu-22.04/4.4/libc++
        token: ${{ secrets.CRANATGH_GITHUB_TOKEN }}
      env:
        PKG_CURRENT_PLATFORM: x86_64-pc-linux-gnu-ubuntu-22.04-libc++
