name: Ubuntu 22.04 s390x, R 4.1
on:
  workflow_dispatch:
  schedule:
    - cron:  '06 23 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/setup-qemu-action@v3
    - name: Check Distro and R version
      run: |
        #
        readRenviron("/etc/os-release")
        if (Sys.getenv("ID") != "ubuntu") stop("Not Ubuntu")
        if (Sys.getenv("VERSION_ID") != "22.04") stop("Not Ubuntu 22.04")
        if (getRversion() < "4.1.0" || getRversion() >= "4.2.0") {
          stop("Not R 4.1.x")
        }
        if (Sys.info()[["machine"]] != "s390x") stop("Not s390x")
      shell: Rscript {0}
    - uses: actions/checkout@v3
    - uses: r-hub/repos/actions/update-repo@main
      with:
        directory: ubuntu-22.04-s390x/4.1
        token: ${{ secrets.CRANATGH_GITHUB_TOKEN }}
