name: Ubuntu 24.04 aarch64, R 4.5
on:
  workflow_dispatch:
  schedule:
    - cron:  '06 23 * * *'

jobs:
  update:
    runs-on: ubuntu-22.04-arm
    container: ghcr.io/r-lib/rig/ubuntu-24.04-release
    steps:
    - name: Install and select R 4.5.x
      run: |
        rig add next
        rig default next
      shell: bash
    - name: Check Distro and R version
      run: |
        #
        readRenviron("/etc/os-release")
        if (Sys.getenv("ID") != "ubuntu") stop("Not Ubuntu")
        if (Sys.getenv("VERSION_ID") != "24.04") stop("Not Ubuntu 24.04")
        if (getRversion() < "4.5.0" || getRversion() >= "4.6.0") {
          stop("Not R 4.6.x")
        }
        if (Sys.info()[["machine"]] != "aarch64") stop("Not aarch64")
      shell: Rscript {0}
    - uses: actions/checkout@v3
    - uses: r-hub/repos/actions/update-repo@main
      with:
        directory: ubuntu-24.04-aarch64/4.5
        token: ${{ secrets.CRANATGH_GITHUB_TOKEN }}
